title: Nipuna Abeysinghe
#logo: /assets/img/logo.png
description: Hands-on mechatronics engineer with 8+ years of experience in manufacturing and production 
environments, including electronics assembly, machinery operation, and process improvement
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
